all_caption: False
dpi: 150
format: pdf
layout: 
  num_row: 1
  num_col: 3
  margin: 0.1
font:
  size: 20
  type: Arial
images:
  - assets/sample01.jpg
  - assets/sample01.jpg
  - assets/sample01.jpg
labels:
    - (a) Ours
    - (b) Method1
    - (C) Method2
ylabels:
    - 
    - 
    - 
